### ISSUE TITLE
[BUG] 似乎依赖部分全局样式

### ISSUE THREAD

**Issue by illusionlie** [illusionlie/key_style_right_click_menu#3]
在测试完成 (原项目的demo html) 后, 在实际环境测试时遇到了 CSS污染 问题, 
可以通过移除项目 CSS 中的 `body`, `html`, `a` 全局样式解决。

然而, 虽然在实际测试中可以正常使用, 在原项目的 demo 中却失效, 
将移除的样式添加进 demo 中可以解决, 但在实际使用时不应该要求用户额外添加或检查全局资源

相关样式: 
```css
            body,html{margin:0;padding:0;width:100%;height:100%}
            body{font-size:1.4rem;background:#494a5f url() no-repeat fixed;background-size:cover;font-family:"Segoe UI","Lucida Grande",Helvetica,Arial,"Microsoft YaHei",FreeSans,Arimo,"Droid Sans","wenquanyi micro hei","Hiragino Sans GB","Hiragino Sans GB W3",FontAwesome,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
            a{text-decoration:none;outline:0}
```

**Comment by illusionlie** [comment]
fixed in https://github.com/illusionlie/key_style_right_click_menu/commit/c460d3ab52b33c6e633d6d235ddb3f0b95ae864a

**Comment by illusionlie** [comment]
必须添加
```css
html, body {
    height: 100%;
}
```
